# Generated by Django 3.1.2 on 2021-12-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='imagenes', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=150)),
                ('fechaNacimiento', models.DateField(auto_now=True)),
                ('fechaAlta', models.DateField(auto_now=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=150)),
                ('biografia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('fechaInicio', models.DateField(auto_now=True)),
                ('fechaFin', models.DateField(auto_now=True)),
                ('informeFinal', models.CharField(max_length=255)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.categoria')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaDescripcion', models.DateField(auto_now=True)),
                ('rol', models.CharField(max_length=100)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cliente')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.usuario'),
        ),
    ]
