# Generated by Django 3.1.2 on 2022-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20220112_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
