# Generated by Django 3.1.2 on 2022-01-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20220113_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participa',
            old_name='fechaDescripcion',
            new_name='fechaInscripcion',
        ),
    ]
