# Generated by Django 3.1.2 on 2022-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20220118_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.FileField(upload_to='imagenes/', verbose_name='Foto'),
        ),
    ]
