# Generated by Django 3.1.2 on 2022-01-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_auto_20220119_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(upload_to='assets/imagenes/', verbose_name='Foto'),
        ),
    ]
