# Generated by Django 3.1.2 on 2022-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_auto_20220119_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'pepe'), (1, 'admin')], default='pepe'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
