# Generated by Django 3.1.2 on 2022-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_auto_20220120_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'cliente'), (3, 'empleado')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ManyToManyField(to='empresa.Role'),
        ),
    ]
