# Generated by Django 3.1.2 on 2022-01-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_auto_20220120_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
