# Generated by Django 3.1.2 on 2022-01-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_auto_20220120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(upload_to='static/assets/imagenes/', verbose_name='Foto'),
        ),
    ]
