# Generated by Django 3.1.2 on 2022-01-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_auto_20220124_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(upload_to='assets/imagenes/', verbose_name='Foto'),
        ),
    ]
