# Generated by Django 3.1.2 on 2022-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0019_auto_20220126_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(unique=True, upload_to='\\img_categorias', verbose_name='Foto'),
        ),
    ]
