# Generated by Django 3.1.2 on 2022-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_auto_20220126_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(unique=True, upload_to='img_categorias/', verbose_name='Foto'),
        ),
    ]
