# Generated by Django 3.1.2 on 2022-01-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_auto_20220126_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(unique=True, upload_to='categorias/', verbose_name='Foto'),
        ),
    ]
