# Generated by Django 3.1.2 on 2022-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_auto_20220126_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
