# Generated by Django 3.1.2 on 2022-02-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0025_auto_20220129_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='fechaInscripcion',
            field=models.DateField(),
        ),
    ]
