# Generated by Django 3.1.2 on 2022-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0026_auto_20220201_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='fechaInscripcion',
            field=models.DateField(verbose_name='Fecha de Inscripción'),
        ),
    ]
