# Generated by Django 3.1.2 on 2022-02-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0027_auto_20220201_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='empresa.proyecto'),
        ),
    ]
