# Generated by Django 3.1.2 on 2022-02-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0028_auto_20220219_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.proyecto'),
        ),
    ]
