# Generated by Django 3.1.2 on 2022-02-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0029_auto_20220220_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresa.cliente'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='empresa.proyecto'),
        ),
    ]
